server:
  port: 8762
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost-02
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      ## 将自己注册到另一台eureka上
      defaultZone: http://eureka-server:8761/eureka/
---
spring:
  profiles: pro
eureka:
  instance:
    hostname: eureka-server-02
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
