spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/newblog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

