spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/newblog
    username: root
    password: root
    #activemq
  activemq:
    broker-url: tcp://eureka-server:61616
    in-memory: true
    pool:
      enabled: false