spring:
  datasource:
#    driver-class-name: net.sf.log4jdbc.DriverSpy
#    url: jdbc:log4jdbc:mysql://localhost:3306/newblog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newblog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 
  #activemq
  activemq:
    broker-url: tcp://eureka-server:61616
    in-memory: true
    pool:
      enabled: false
  #redis
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10
  data:
    solr:
      host: http://127.0.0.1:8081/solr
