server:
  port: 8761

eureka:
  instance:
    hostname: 39.107.79.30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
