server:
  port: 8081

spring:
  profiles: development
  application:
    name: comment
  cloud:
    config:
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/