server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shibo92/blog.git
          search-paths: config-repo/conf
          force-pull: true
          timeout: 120
---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/, http://eureka-server:8762/eureka/
---
spring:
  profiles: pro
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/, http://eureka-server:8762/eureka/
server:
  tomcat:
    max-threads: 5
