server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shibo92/spring-cloud-blog/tree/master/config-repo/conf