server:
  port: 8080

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shibo92/blog.git
          search-paths: config-repo/conf
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/